// @vitest-environment happy-dom
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { BarcodeFormat, MultiFormatWriter } from '@zxing/library';
import { detectBarcodesJs, __resetFallbackReaderForTests } from './imeiBarcodeFallback';
import { classifyScannedValues, hasVerifiedField } from '../domain/imeiScan';

// The bug this guards: on iOS — and especially the INSTALLED PWA, a WebKit web
// view where BarcodeDetector is commonly absent — tier 1 found nothing, so
// every scan fell through to OCR and then to the paid AI tier. Including scans
// of the shop's OWN ZP 450 inventory labels, which carry QR codes.
//
// These tests decode a real QR bitmap end to end. happy-dom has no canvas
// engine, so a minimal stub stands in for getImageData — the pixels are real,
// generated by encoding an actual QR, which is the part that matters.

/** Render a payload to a real QR bitmap, as an RGBA buffer. */
function qrImageData(payload: string, size = 300): ImageData {
  const matrix = new MultiFormatWriter().encode(payload, BarcodeFormat.QR_CODE, size, size, new Map());
  const w = matrix.getWidth();
  const h = matrix.getHeight();
  const data = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      const v = matrix.get(x, y) ? 0 : 255;
      data[i] = v; data[i + 1] = v; data[i + 2] = v; data[i + 3] = 255;
    }
  }
  return { data, width: w, height: h, colorSpace: 'srgb' } as ImageData;
}

/** A canvas whose 2D context returns the given pixels — happy-dom has no real one. */
function canvasOf(image: ImageData): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = image.width;
  canvas.height = image.height;
  canvas.getContext = (() => ({ getImageData: () => image, drawImage: () => {} })) as never;
  return canvas;
}

beforeEach(() => { __resetFallbackReaderForTests(); });

describe('JS barcode fallback — reads the codes the native detector would', () => {
  it("decodes a QR carrying an IMEI, the format the shop's own inventory labels use", async () => {
    // services/labelLayout.ts prints the IMEI/serial into the label's QR; this
    // is exactly that payload.
    const imei = '356789101234563';
    const values = await detectBarcodesJs(canvasOf(qrImageData(imei)));
    expect(values).toEqual([imei]);
  });

  it('feeds results through the SAME Luhn/normalisation path, never accepting raw output', async () => {
    // 356789101234563 is Luhn-valid; the scanner must treat it as verified via
    // domain/imeiScan.ts, not because the decoder said so.
    const fields = classifyScannedValues(await detectBarcodesJs(canvasOf(qrImageData('356789101234563'))));
    expect(hasVerifiedField(fields)).toBe(true);
    expect(fields[0].key).toBe('imei1');
    expect(fields[0].value).toBe('356789101234563');

    // A Luhn-FAILING 15-digit read decodes fine but must NOT come back verified —
    // the decoder is not the authority on whether a number is real.
    const bad = classifyScannedValues(await detectBarcodesJs(canvasOf(qrImageData('356789101234567'))));
    expect(bad[0].verified).toBe(false);
    expect(hasVerifiedField(bad)).toBe(false);
  });

  it('decodes a QR carrying a repair/SKU string, not just digits', async () => {
    expect(await detectBarcodesJs(canvasOf(qrImageData('FTT-0000029')))).toEqual(['FTT-0000029']);
  });

  it('returns [] for a frame with no code — a miss, not an error', async () => {
    const blank: ImageData = {
      data: new Uint8ClampedArray(100 * 100 * 4).fill(255), width: 100, height: 100, colorSpace: 'srgb',
    } as ImageData;
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(await detectBarcodesJs(canvasOf(blank))).toEqual([]);
    // NotFoundException is the normal "nothing in this frame" signal — most
    // live-loop frames hit it, so it must not spam the console.
    expect(spy).not.toHaveBeenCalled();
    spy.mockRestore();
  });

  it('returns [] rather than throwing when the canvas has no readable pixels', async () => {
    const canvas = document.createElement('canvas');
    canvas.width = 0;
    canvas.height = 0;
    expect(await detectBarcodesJs(canvas)).toEqual([]);
  });

  it('returns [] when a tainted canvas refuses getImageData, without throwing', async () => {
    const canvas = document.createElement('canvas');
    canvas.width = 10; canvas.height = 10;
    canvas.getContext = (() => ({ getImageData: () => { throw new Error('SecurityError'); } })) as never;
    expect(await detectBarcodesJs(canvas)).toEqual([]);
  });
});
