import * as FileSystem from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { TESTS } from '../tests/registry';
import type { DeviceReport } from '../types';
import { STATUS_META } from '../components/ui';

const STATUS_HTML_COLOR: Record<string, string> = {
  pass: '#1E9E52',
  fail: '#C0392B',
  skip: '#B8860B',
  untested: '#7A7A7A',
};

/** Build a clean, printable HTML document for a report. */
export function buildReportHtml(report: DeviceReport): string {
  const { summary } = report;
  const created = new Date(report.createdAt).toLocaleString();

  const rows = TESTS.map((t) => {
    const r = report.results[t.id];
    const status = r?.status ?? 'untested';
    const color = STATUS_HTML_COLOR[status];
    const notes = r?.notes ? `<div class="notes">${escapeHtml(r.notes)}</div>` : '';
    return `
      <tr>
        <td class="cat">${escapeHtml(t.category)}</td>
        <td>${escapeHtml(t.title)}${notes}</td>
        <td><span class="badge" style="background:${color}">${STATUS_META[status].label}</span></td>
      </tr>`;
  }).join('');

  return `<!doctype html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { font-family: -apple-system, Helvetica, Arial, sans-serif; }
    body { color:#111; padding:24px; }
    h1 { margin:0 0 4px; font-size:22px; }
    .sub { color:#666; font-size:13px; margin-bottom:16px; }
    .cards { display:flex; gap:10px; margin:16px 0; }
    .card { flex:1; border:1px solid #ddd; border-radius:10px; padding:10px 12px; text-align:center; }
    .card .n { font-size:26px; font-weight:800; }
    .card .l { font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#666; }
    table { width:100%; border-collapse:collapse; margin-top:8px; }
    th { text-align:left; font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#666; border-bottom:2px solid #eee; padding:8px 6px; }
    td { padding:8px 6px; border-bottom:1px solid #eee; font-size:13px; vertical-align:top; }
    td.cat { color:#888; font-size:11px; white-space:nowrap; }
    .badge { color:#fff; padding:2px 10px; border-radius:999px; font-size:11px; font-weight:700; }
    .notes { color:#888; font-size:11px; margin-top:2px; }
    .footer { margin-top:20px; color:#999; font-size:11px; }
  </style></head><body>
    <h1>FTT Device Diagnostics Report</h1>
    <div class="sub"><strong>${escapeHtml(report.deviceLabel)}</strong> · ${created}</div>
    <div class="cards">
      <div class="card"><div class="n" style="color:${STATUS_HTML_COLOR.pass}">${summary.pass}</div><div class="l">Pass</div></div>
      <div class="card"><div class="n" style="color:${STATUS_HTML_COLOR.fail}">${summary.fail}</div><div class="l">Fail</div></div>
      <div class="card"><div class="n" style="color:${STATUS_HTML_COLOR.skip}">${summary.skip}</div><div class="l">Skip</div></div>
      <div class="card"><div class="n" style="color:${STATUS_HTML_COLOR.untested}">${summary.untested}</div><div class="l">Untested</div></div>
    </div>
    <table>
      <thead><tr><th>Category</th><th>Test</th><th>Result</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="footer">${summary.pass}/${summary.total} tests passed. Generated by FTT Device Diagnostics.</div>
  </body></html>`;
}

/** Render to PDF and open the share sheet (also supports AirPrint via share). */
export async function shareReportPdf(report: DeviceReport): Promise<void> {
  const html = buildReportHtml(report);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf' });
  }
}

/** Send the report straight to an AirPrint printer. */
export async function printReport(report: DeviceReport): Promise<void> {
  await Print.printAsync({ html: buildReportHtml(report) });
}

/** Export the raw report JSON and open the share sheet. */
export async function shareReportJson(report: DeviceReport): Promise<void> {
  const safe = report.deviceLabel.replace(/[^a-z0-9]+/gi, '_').slice(0, 40) || 'report';
  const uri = `${FileSystem.cacheDirectory}${safe}_${report.id}.json`;
  await FileSystem.writeAsStringAsync(uri, JSON.stringify(report, null, 2), {
    encoding: FileSystem.EncodingType.UTF8,
  });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/json', UTI: 'public.json' });
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
